services:
  postgres:
    image: postgres:17
    container_name: spring-jpa-postgres
    environment:
      POSTGRES_DB: spring_jpa
      POSTGRES_USER: spring_user
      POSTGRES_PASSWORD: spring_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spring_user -d spring_jpa"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: spring-jpa-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVER_PORT: 8080
      JAVA_TOOL_OPTIONS: -Xms256m -Xmx512m

#      SPRING_PROFILES_ACTIVE: seed
      SPRING_JPA_HIBERNATE_SHOW_SQL: true

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spring_jpa
      SPRING_DATASOURCE_USERNAME: spring_user
      SPRING_DATASOURCE_PASSWORD: spring_pass
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info
      MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data: